url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Quantum Nano-Optics group" # the name of your site, e.g. ACME Corp.
description: "Explore physics in low dimensions"
