menu:
- {name: 'member', url: '/member'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}

member:
- {name: 'SeokJae Yoo', title: 'Professor', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: '(032) 860-7658', email: 'seokjaeyoo@inha.ac.kr', office: '5S303', image: 'https://physics.inha.ac.kr/user/photo/fee2ab236d1148df930c32eae14c2a1c5501c5321778232a9d29871f09358ff6_prof.jpg', url: 'professor'}

- {name: 'DongJun Kang', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'qqsscc0310@inha.edu', office: '5N313', url: 'graduate-student'}
- {name: 'YoonYeong Ko', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'b46541@naver.com', office: '5N313', url: 'graduate-student'}
- {name: 'Kyung Hoon Kim', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'kkh6972@naver.com', office: '5N313', url: 'graduate-student'}
- {name: 'KiBack Kim', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: '1991kln@naver.com', office: '5N313', url: 'graduate-student'}
- {name: 'Eun Su Jeon', title: 'Student', department: 'Mathematics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'lasttwice@inha.edu', office: '5N313', url: 'graduate-student'}
- {name: 'SeungWoo Choi', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'reungwoo0127@gmail.com', office: '5N313', url: 'graduate-student'}
- {name: 'Jingyu Youn', title: 'Student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: '
yjg4073@gmail.com', office: '5N313', url: 'graduate-student'}

social:
- {icon: 'google', link: 'https://scholar.google.com/citations?user=ykNjjx0AAAAJ&hl=en'}
- {icon: 'id-card', link: 'https://orcid.org/0000-0002-6438-7123'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/seokjaeyoo/'}
- {icon: 'github', link: 'https://github.com/seokjaeyoo/yoo'}
