menu:
- {name: 'member', url: '/member'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}

pi:
- {name: 'SeokJae Yoo', title: 'Assistant Professor', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: '(032) 860-7658', email: 'seokjaeyoo@inha.ac.kr', office: '5S303', image: 'assets/img/seokjae.jpg', url: 'professor'}

member:
- {name: 'Chibuzo Onwukaeme', title: 'Postdoc', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'hyginusonwuka@gmail.com', office: '5N302', url: 'postdoc', image: 'assets/img/Chibuzo.jpg'}
- {name: 'Seokhyun Jang', title: 'Graduate student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'seokhyun1130@daum.net', office: '5N302', url: 'graduate-student', image: 'assets/img/dongjun.jpg'}
- {name: 'DongJun, Kang', title: 'Graduate student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'qqsscc0310@inha.edu', office: '5N302', url: 'graduate-student', image: 'assets/img/dongjun.jpg'}
- {name: 'YoonYeong, Ko', title: 'Graduate student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'b46541@naver.com', office: '5N302', url: 'graduate-student', image: 'assets/img/YoonYeong.jpg'}
- {name: 'Jae Jin, Lee', title: 'Graduate student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'b46541@naver.com', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}
- {name: 'Kang Ryeol, Lee', title: 'Grad student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: '
wnrrpej@naver.com', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}
- {name: 'Eun Su, Jeon', title: 'Grad student', department: 'Mathematics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'lasttwice@inha.edu', office: '5N302', url: 'graduate-student', image: 'assets/img/EunSu.JPG'}
- {name: 'Kyeong Pyo, Jeon', title: 'Grad student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: '
jkprudvy@naver.com', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}
- {name: 'SeungWoo Choi', title: 'Undergrad student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'reungwoo0127@inha.edu', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}
- {name: 'DongSung Lee', title: 'Undergrad student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'dongsung7533@naver.com', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}
- {name: 'KiJeong Park', title: 'Undergrad student', department: 'Physics', institution: 'Inha University', institution_address: 'address', phone: 'NA', email: 'pk2j0905@gmail.com', office: '5N302', url: 'graduate-student', image: 'assets/img/SymbolMark_tran.png'}

alumni:
- {name: 'Jingyu Youn', period: 'Undergrad internship', title: 'LG Display'}

social:
- {icon: 'google', link: 'https://scholar.google.com/citations?user=ykNjjx0AAAAJ&hl=en'}
- {icon: 'id-card', link: 'https://orcid.org/0000-0002-6438-7123'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/seokjaeyoo/'}
- {icon: 'github', link: 'https://github.com/seokjaeyoo/yoo'}
